#! /bin/sh
# Mil4ne - Bspwm config

$HOME/.config/polybar/launch.sh --blocks &
xsetroot -cursor_name left_ptr &

pgrep -x sxhkd > /dev/null || sxhkd &


wmname LG3D &
vmware-user-suid-wrapper &

bspc monitor -d 1 2 3 4 5 6

bspc config top_padding 30
bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config normal_border_color "#043B32"
#bspc config active_border_color "#5294E2"
bspc config focused_border_color "#0BBDA2"
#bspc config presel_feedback_color "#81a1c1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill ~/Wallpapers/wall.png &
